module.exports = {
    'connection': {
        'host' : 'localhost',
        'user' : 'root',
        'password' : 'mysqlRootPassword',
        'connectionLimit': 500
    },
    'database' :  'IFS',
    'users_table' : 'users',
    'survey_table': 'survey',
    'survey_results_table': 'surveyResult',
    'survey_preferences_table': 'survey_preferences',
    'feedback_table':'feedback',
    'feedback_interaction_table': 'feedback_interaction',
    'users_interation_table': 'userInteractions',
    'user_feedback_table' : 'userFeedback',
    'preferences_table': 'preferences',
    'question_table': 'questions',
    'submission_table': 'submission',
    'student_table': 'student',
    'class_table': 'class',
    'student_class_table': 'student_class',
    'assignment_table': 'assignment',
    'class_skill_table': 'class_skill',
    'student_skill_table': 'student_skill',
    'upcoming_event_table': 'upcoming_event',
    'role_table': 'roles',
    'user_role_table': 'user_role',
    'feedback_stats_table':'feedback_stats',
};
